### ISSUE TITLE
pagecontrol 的点点算法错误

### ISSUE THREAD

**Issue by 123456789lk** [12207480/TYCyclePagerView#13]
在 layoutIndicatorViews  
{
case UIControlContentHorizontalAlignmentCenter：
orignX = (CGRectGetWidth(self.frame) - (_indicatorViews.count - 1) * (_pageIndicatorSize.width + _pageIndicatorSpaing) - _currentPageIndicatorSize.width )/2;

for ()
{
     indicatorView.frame = CGRectMake(orignX , centerY - size.height/2, size.width, size.height);
        
        orignX += size.width + pageIndicatorSpaing;
}
}

**Comment by 123456789lk** [comment]
在这里我只看了我所用到的地方存在的问题

**Comment by 12207480** [comment]
哪个地方错了请说明下
