### ISSUE TITLE
在Xcode 7中编译错误,没有做__IPHONE_OS_VERSION_MAX_ALLOWED判断

### ISSUE THREAD

**Issue by neters** [12207480/TYCyclePagerView#15]
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 100000
    if ([collectionView respondsToSelector:@selector(setPrefetchingEnabled:)]) {
        collectionView.prefetchingEnabled = NO;
    }
#endif

**Comment by 12207480** [comment]
已经不用xcode7编译了
