### ISSUE TITLE
延时加载数据后，无法滚动

### ISSUE THREAD

**Issue by BillHu** [12207480/TYCyclePagerView#17]
用demo运行，ViewController里用延时加载的loadData方法，无法拖动cell。如果将numberOfItemsInPagerView返回值改为固定值则可拖动。

**Comment by BillHu** [comment]
手机是iPhone 6s，版本11.1.2。

**Comment by 12207480** [comment]
我看看

**Comment by 12207480** [comment]
已修复 你试试看
