### ISSUE TITLE
你好，cell 对齐方式，可以让它居下对齐吗，里面有图，如果可以，改怎么改？

### ISSUE THREAD

**Issue by Casabalnca** [12207480/TYCyclePagerView#30]
如图所示，

![2ea3c83a-173b-4217-9a33-a600fb8cb4e6](https://user-images.githubusercontent.com/8315500/35206037-b517dafa-ff74-11e7-845f-fddd2c432e33.png)

**Comment by Casabalnca** [comment]
宽高，都是有缩放的，但是位置是居下对齐

**Comment by 12207480** [comment]
需要自己写layout了

**Comment by Casabalnca** [comment]
你好，因为cell 的高度是不确定的，我想从cell  的layoutSubviews 方法里面，来计算pageview 的高度，请问该如何获取到pageview？因为我发现要通过 修改layout  pageView.layout.itemSize = CGSizeMake(self.hx_w, self.hx_h - 80);
//        [pageView setNeedUpdateLayout];
但是目前我不知道该怎么获取到pageView

**Comment by Casabalnca** [comment]
你好，可以加qq 704379869吗，方便和您交流

**Comment by 12207480** [comment]
delegate  - (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView;
