### ISSUE TITLE
- (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView 这个代理方法只走了一遍，并且

### ISSUE THREAD

**Issue by Casabalnca** [12207480/TYCyclePagerView#33]
- (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView 这个代理方法只走了一遍，并且 我需要针对每一个cell 进行layout，请问该怎么搞？因为每一个cell 的高度都是不确定的

**Comment by 12207480** [comment]
每个cell 高度不一样这个做不了
