### ISSUE TITLE
现在cell 是居中的，我想写一个枚举，通过枚举，实现居中，居上，居下，请问改那个地方？

### ISSUE THREAD

**Issue by Casabalnca** [12207480/TYCyclePagerView#35]
RT

**Comment by Casabalnca** [comment]
想让他是线性布局，并且是居下的

**Comment by Casabalnca** [comment]
我知道你设置了一个缩放的最小值，
我在缩放和移动的最后，又设置了一下frame，代码如下
   attributes.transform = transform;
    attributes.alpha = alpha;
    CGRect visibleRect = {self.collectionView.contentOffset,self.collectionView.bounds.size};
    attributes.frame = CGRectMake(attributes.frame.origin.x, visibleRect.size.height - attributes.frame.size.height, attributes.frame.size.width, attributes.frame.size.height);

发现结果并非我所愿，当前的cell 是居下了，移动过程中大小也是一样的，但是移动过去之后，上一个的cell，还是没有居中，我感觉是不是需求是矛盾的？这个功能可能实现吗？

**Comment by 12207480** [comment]
有图没

**Comment by Casabalnca** [comment]
![55448946-d582-45bf-bf61-960c39b572c8](https://user-images.githubusercontent.com/8315500/35491941-a642153e-04e4-11e8-9df2-9fe5986856d0.png)

**Comment by Casabalnca** [comment]
既想要缩放的动画，又想要居下，感觉有点矛盾啊，其实就是和的demo 动画效果一样，只不过，cell 都是居下的

**Comment by Casabalnca** [comment]
这样的应该可以只需要修改cell 的Y值就可以了吧，但是通过如上代码，当前的cell 是居下了，但是其他的都还是居中。。。

**Comment by Casabalnca** [comment]
所以问问你，在哪里修改所有的cell 的Y值

**Comment by Casabalnca** [comment]
layout.itemVerticalCenter = NO;

**Comment by Casabalnca** [comment]
按道理来讲，缩放之后，调整frame 就可以了，为啥不行。。。
