### ISSUE TITLE
你好，因为我的cell 的高度 是根据数据来计算的，请问，改如何创建layout？？？

### ISSUE THREAD

**Issue by Casabalnca** [12207480/TYCyclePagerView#36]
- (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView 

因为你这个layout ，我发现这个代理方法只调用一次，这个请问怎么改？？？

**Comment by Casabalnca** [comment]
也就是我想一个cell 对应一个layout ，这个改怎么改？？？

**Comment by Casabalnca** [comment]
- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath
重写的这个方法，为啥不调用啊

**Comment by 12207480** [comment]
做不到
