### ISSUE TITLE
有个警告This is likely occurring because the flow layout...

### ISSUE THREAD

**Issue by wangfaguo** [12207480/TYCyclePagerView#4]
This is likely occurring because the flow layout subclass SXLineLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them

需要修改为
- (NSArray<UICollectionViewLayoutAttributes *> *)layoutAttributesForElementsInRect:(CGRect)rect {
    NSArray *attributesArray =  [[NSArray alloc] initWithArray:[super layoutAttributesForElementsInRect:rect] copyItems:YES];
    if (_delegateFlags.applyTransformToAttributes || _layout.layoutType != TYCyclePagerTransformLayoutNormal) {
        CGRect visibleRect = {self.collectionView.contentOffset,self.collectionView.bounds.size};
        for (UICollectionViewLayoutAttributes *attributes in attributesArray) {
            if (!CGRectIntersectsRect(visibleRect, attributes.frame)) {
                continue;
            }
            if (_delegateFlags.applyTransformToAttributes) {
                [_delegate pagerViewTransformLayout:self applyTransformToAttributes:attributes];
            }else {
                [self applyTransformToAttributes:attributes layoutType:_layout.layoutType];
            }
        }
    }
    return attributesArray;
}

**Comment by 12207480** [comment]
可以

**Comment by 12207480** [comment]
已修复
