### ISSUE TITLE
询问一下计算是否有误

### ISSUE THREAD

**Issue by AbeiOS** [12207480/TYCyclePagerView#41]
在 - caculateIndexSectionWithOffsetX 方法中，计算 itemIndex 的算法里
代码是这样的 NSInteger itemIndex = (middleOffset - leftEdge **+ layout.minimumInteritemSpacing / 2**) / itemWidth;
其中的  **+ layout.minimumInteritemSpacing / 2** 是否应该改成 **- layout.itemSize.width / 2** ?

期待你的回复

**Comment by 12207480** [comment]
没有错
