### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by BruceWee01** [12207480/TYCyclePagerView#42]
你好，如果我在某个页面用到了轮播，但是这个页面需要在- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    
}
这个方法里做某些事情，只要用到你的框架实现轮播的页面实现- (void)scrollViewDidScroll:(UIScrollView *)scrollView
{
    
}这个代理方法就会崩溃呢？

**Comment by 12207480** [comment]
不要用scrollview的代理 PagerView本身就有类似的代理方法- (void)pagerViewDidScroll:(TYCyclePagerView *)pageView;
