### ISSUE TITLE
请问可以通过什么方式来阻止复用的问题?

### ISSUE THREAD

**Issue by sushushu** [12207480/TYCyclePagerView#45]
我的轮播cell里面由3个UIImageView和1个AVPlayer, AVPlayer的播放layer在UIImageView上面.
现在遇到的问题是重复轮播几遍之后3个UIImageView上面都播放了视频,
http://ww1.sinaimg.cn/large/0061KoHBgy1fpofm8uwfrj30q217g4nm.jpg
感谢.

**## pagerView delegate**
```
- (UICollectionViewCell *)pagerView:(TYCyclePagerView *)pagerView cellForItemAtIndex:(NSInteger)index {
    JTZbannerCell *cell = [pagerView dequeueReusableCellWithReuseIdentifier:@"JTZbannerCell" forIndex:index];

    NSString *type = self.bannerDataSource[index];
    
    cell.type = type;

    return cell;
}
```

**## setType**

```
- (void)setType:(NSString *)type {
    _type = type;

    if ([type containsString:@"mp4"]) {
        [self playerLayer];
        [self.player play];
    } else {
        [self.imageView setImageWithURLString:type placeholderImageName:@"home_p_bg"];
    }
}
```

**Comment by 12207480** [comment]
不使用 [pagerView dequeueReusableCellWithReuseIdentifier:@"JTZbannerCell" forIndex:index]；
自己创建一个数组保存cell 每次cellForItemAtIndex 从数组里取

**Comment by sushushu** [comment]
这是我拿数据的时候:
![Alt text](http://ww1.sinaimg.cn/large/0061KoHBgy1fpu36xgb6zj31f60ja78t.jpg "optional title")

这是cellForItemAtIndex里面做的操作:
![Alt text](http://ww1.sinaimg.cn/large/0061KoHBgy1fpu3be13r6j31lw0c8774.jpg "optional title")

我不使用 [pagerView dequeueReusableCellWithReuseIdentifier:@"JTZbannerCell" forIndex:index]；
自己创建一个数组保存cell 每次cellForItemAtIndex 从数组里取这样做似乎还是不行,会导致崩溃说必须实现dequeueReusableCellWithReuseIdentifier:方法:
` *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -`

打扰您了,很想解决这个问题.希望得到您的解答~

**Comment by sushushu** [comment]
@12207480

**Comment by sushushu** [comment]
@12207480

**Comment by sushushu** [comment]
还是阻止不了复用问题

**Comment by 12207480** [comment]
我有空看看

**Comment by 12207480** [comment]
register cell 了 没？

**Comment by sushushu** [comment]
嗯 您有空再帮忙看看就好了,
懒加载的时候:
```
 // registerClass
 [_adScrollViewHead registerClass:[JTZbannerCell class] forCellWithReuseIdentifier:@"JTZbannerCell"];
```

pagerView cellForItemAtIndex:代理方法
```
- (UICollectionViewCell *)pagerView:(TYCyclePagerView *)pagerView cellForItemAtIndex:(NSInteger)index {
    JTZbannerCell *cell = [pagerView dequeueReusableCellWithReuseIdentifier:@"JTZbannerCell" forIndex:index];
   return cell;
}
```

**Comment by sushushu** [comment]
@12207480

**Comment by 12207480** [comment]
可以写个demo给我不

**Comment by sushushu** [comment]
https://github.com/sushushu/TYCyclePagerViewDemo  @12207480  您好,demo在这里,我是视频和图片都会出现在banner里面,当数据超过4张(4张没问题)就会出现复用的问题.

**Comment by sushushu** [comment]
@12207480

**Comment by 12207480** [comment]
还在不，这里有个解决方法，虽然不太好，就是每个cell 注册的不同的id，即可避免复用
 [_adScrollViewHead registerClass:[JTZbannerCell class] forCellWithReuseIdentifier:@"JTZbannerCell1"];
 [_adScrollViewHead registerClass:[JTZbannerCell class] forCellWithReuseIdentifier:@"JTZbannerCell2"];

**Comment by sushushu** [comment]
感谢,注册不同的id这种方式我试过,会崩溃.我用了另外一种办法也达到了需要的效果.
再次感谢您的框架.这个issue可以关闭了.

```
- (UICollectionViewCell *)pagerView:(TYCyclePagerView *)pagerView cellForItemAtIndex:(NSInteger)index {
    JTZbannerCell *cell = [pagerView dequeueReusableCellWithReuseIdentifier:@"JTZbannerCell" forIndex:index];
    JTZBannerModel *model = [JTZBannerModel mj_objectWithKeyValues:self.bannerDataSource[index]];
    cell.model = nil; // 修复复用问题的核心代码
    cell.model = model;
    return cell;
}
```

**Comment by 12207480** [comment]
不错
