### ISSUE TITLE
滑到最后一个 reload一下 会居中显示

### ISSUE THREAD

**Issue by 806048441** [12207480/TYCyclePagerView#49]
infiniteloop autoscroll itemhor…center 为no 滑到最后一个 reload一下 会居中显示

**Comment by 12207480** [comment]
![image](https://user-images.githubusercontent.com/6346030/39284227-e1053d78-4944-11e8-94e9-7c8145688304.png)
没有问题 reloadData 会重新生成layout 默认设置yes
如果不想重新生成可以用layout updateData

**Comment by 12207480** [comment]
已经修复

**Comment by 806048441** [comment]
多谢 多谢
