### ISSUE TITLE
加载数据 bug && Cocoapods 上无法搜索到

### ISSUE THREAD

**Issue by Connerli** [12207480/TYCyclePagerView#5]
如果不是直接加载数据，从网络上请求数据后赋值，也就是延迟几秒加载数据，视图会偏移，并且定时器停掉了
![image](https://user-images.githubusercontent.com/16755393/30053175-7598a2ce-925a-11e7-9972-7ef1fe1670a6.png)

![image](https://user-images.githubusercontent.com/16755393/30053207-92e367ec-925a-11e7-963c-a7c20265653f.png)

**Comment by 12207480** [comment]
pod update repo

**Comment by Connerli** [comment]
pod setup ?

**Comment by Connerli** [comment]
pod repo update, 我第一次查找不到时候，已经更新了一下repo，但是还是找不到，可能你配置文件或者哪里有问题，你可以在别的电脑search 一下试试，因为在你本地可能已经有了这个库的索引podspec 文件了，install 是可以install 下来，search 不到。
主要还是数据延迟后定时器停止和图片布局问题。

**Comment by HatsuneMikuV** [comment]
这个有解决吗？我也遇到了，请问修复了吗？

**Comment by HatsuneMikuV** [comment]
@Connerli @12207480

**Comment by Connerli** [comment]
@12207480 目前我先换了个轮播图，项目时间紧，没来得及看源码，有时间了再仔细看下。

**Comment by Connerli** [comment]
@HatsuneMikuV 还没来得及看源码，哪里问题，有时间了再看下
@12207480 作者修复了这个bug，麻烦提示一下，谢谢

**Comment by 12207480** [comment]
cocoapods 上已经有了https://cocoapods.org/?q=TYCyclePagerView

**Comment by 12207480** [comment]
有没有复现的demo

**Comment by HatsuneMikuV** [comment]
我是在工程里使用出现的，只有5s出现了，5s以上设备没发现这个问题
@Connerli @12207480

**Comment by Connerli** [comment]
@12207480 直接使用你的demo，加载数据的时候，你用做个延迟调用刷新数据，就出现了，不需要别的demo。

**Comment by 12207480** [comment]
已修复

**Comment by HatsuneMikuV** [comment]
ok
66666

**Comment by Connerli** [comment]
@12207480 pod search 问题有修复么？感觉可能是你的podSpec 文件写的有问题，有没有让别人测试一下，能否搜到？

**Comment by 12207480** [comment]
可以 搜到 你先可以pod setup  更新下
