### ISSUE TITLE
scrollToItemAtIndex: item indexSection is invalid!

### ISSUE THREAD

**Issue by JIANHUI2015** [12207480/TYCyclePagerView#51]
报错
```
scrollToItemAtIndex: item indexSection is invalid!
```

注意到indexSection初始化时，index和section都等于-1，所以indexSection是无效的
我添加到某些视图上可以正常工作，某些视图上不可行，似乎和`layoutSubviews`的调用时机有关

**Comment by 12207480** [comment]
reloadData后在调用吗

**Comment by JIANHUI2015** [comment]
我在TYCyclePagerView上再封装了一层View（比如该类叫BannerView），做法是将TYCyclePagerView添加到BannerView上。
如果直接将BannerView添加到Controller的View上，等网络请求回调后再reloadData，就会出现上述问题。
我修改为：在网络请求回调后再添加BannerView则可以成功工作。

**Comment by 12207480** [comment]
什么时候修改的frame？

**Comment by yongFine** [comment]
[UIView animateWithDuration:0 animations:^{
        [_pagerView reloadData];
    } completion:^(BOOL finished) {
        [_pagerView scrollToItemAtIndex:index animate:NO];
    }];可解决二次封装

**Comment by JIANHUI2015** [comment]
viewDidLoad里设置的frame

**Comment by JIANHUI2015** [comment]
viewDidLoad里面设置了Frame，然后发起网络请求，有数据则reloadData，没数据则 TYCyclePagerView.hidden = YES，大部分情况下都可以成功工作，遇过几次会报错`scrollToItemAtIndex: item indexSection is invalid!`，无法滚动Banner。  我也没办法复现这个错误~只能随机出现

**Comment by JIANHUI2015** [comment]
我找到原因了，跟你的代码没关系，是我的业务比较复杂导致出错~ 我在TYCyclePagerView是隐藏的情况下reloadData，然后再TYCyclePagerView.hidden = NO； 已解决~ 感谢

**Comment by JIANHUI2015** [comment]
我找到原因了，跟你的代码没关系，是我的业务比较复杂导致出错~ 我在TYCyclePagerView是隐藏的情况下reloadData，然后再TYCyclePagerView.hidden = NO，这样子就出错了。

现在已解决~ 感谢
