### ISSUE TITLE
如何修改类型

### ISSUE THREAD

**Issue by jiaohonganGitHub** [12207480/TYCyclePagerView#59]
我想默认TYCyclePagerTransformLayoutLinear类型 
我在初始化的的时候 _pagerView.layout.layoutType = TYCyclePagerTransformLayoutLinear; 并不管用啊
能告诉怎么默认TYCyclePagerTransformLayoutLinear类型么

**Comment by 12207480** [comment]
代理里面有方法

**Comment by jiaohonganGitHub** [comment]
得常感谢

**Comment by jiaohonganGitHub** [comment]
非常感谢
