### ISSUE TITLE
GIF问题反馈

### ISSUE THREAD

**Issue by LazyScream** [12207480/TYCyclePagerView#63]
大神您好：
我使用了您的项目来开发Banner，并把您的TYCyclePagerView设置在TableView中的Row0 
图片的载入我使用喵神的Kingfisher来加载「GIF」
主要问题：只要触发TableView的ReloadData方法时，TYCyclePagerView会瞬间变成空白，但过了几秒钟并自动滚动后又会载入(isInfiniteLoop 为 true)该GIF。
但，如果单纯载入JPG却没有这个问题，还请您解惑 谢谢！

**Comment by 12207480** [comment]
有demo 吗

**Comment by LazyScream** [comment]
https://share.weiyun.com/5tKyY9s
如果可以，或许我们加入QQ沟通也不错
您辛苦了，我可以打赏
若您愿意，请加入我QQ : 3410925895 谢谢

**Comment by LazyScream** [comment]
您可以顺利下载这个Demo吗？

**Comment by 12207480** [comment]
作为cell 由于重用的机制 你需要缓存这个cell

**Comment by LazyScream** [comment]
谢谢协助
