### ISSUE TITLE
通过代码控制滚动

### ISSUE THREAD

**Issue by keyjacky** [12207480/TYCyclePagerView#65]
貌似现有 API 不能实现通过代码滚动到指定的 index 希望跟进一下

**Comment by 12207480** [comment]
/**
 scroll to item at index
 */
- (void)scrollToItemAtIndex:(NSInteger)index animate:(BOOL)animate;

/**
 scroll to next or pre item
 */
- (void)scrollToNearlyIndexAtDirection:(TYPagerScrollDirection)direction animate:(BOOL)animate;
