### ISSUE TITLE
在iphonex模拟器不进layoutforpageview方法，导致布局有问题，效果图如下

### ISSUE THREAD

**Issue by bianxiang** [12207480/TYCyclePagerView#66]
![image](https://user-images.githubusercontent.com/16380379/48061171-15951c00-e1f9-11e8-8496-9d85cd8adf4e.png)

**Comment by bianxiang** [comment]
没有 但是默认不调用应该也没有问题吧？比如系统的tableview

**Comment by 12207480** [comment]
必须要调用
