### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tianxiawoyougood** [12207480/TYCyclePagerView#67]
0 libobjc.A.dylib | objc_retain + 16
1 newhwmc | -[TYCyclePagerView addCollectionView] (TYCyclePagerView.m:102)
2 newhwmc | -[TYCyclePagerView initWithFrame:] (TYCyclePagerView.m:75)
3 newhwmc | -[HWSelBannerCell bannerView] (HWSelBannerCell.m:170)
4 newhwmc | -[HWSelBannerCell setupUI] (HWSelBannerCell.m:48)
5 newhwmc | -[HWSelBannerCell initWithFrame:] (HWSelBannerCell.m:39)
6 UIKit | -[UICollectionView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:] + 892
7 UIKit | -[UICollectionView dequeueReusableCellWithReuseIdentifier:forIndexPath:] + 180
8 newhwmc | -[HWSelGoodsController collectionView:cellForItemAtIndexPath:] (HWSelGoodsController.m:0)
9 UIKit | -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:] + 432

页面整体是一个collectionView。TYCyclePagerView放到第一个cell上面做轮播图。线上崩溃日志中找到了这个崩溃信息。

**Comment by 12207480** [comment]
看不出来 问题
