### ISSUE TITLE
有一个小的体验问题

### ISSUE THREAD

**Issue by Saraca** [12207480/TYCyclePagerView#69]
当item的size很小时，滑动的体验我感觉不是很好，不太流畅，有什么优化的方法吗，还是我使用的姿势不对

**Comment by Saraca** [comment]
是快速滑动的时候

**Comment by Saraca** [comment]
就是把item调这么小后，用力快速滑的时候感觉不太流畅，我想让它有一定的减速过程，现在它是立即停在某个item的位置。
![image](https://user-images.githubusercontent.com/5137817/49125654-c0ca5a00-f2fb-11e8-8928-9dbc9cb09236.png)

**Comment by GeraldAs** [comment]
> 这个会滚到最近的cell

如何让滚动事件继续, 直至滚动快消失时定位到最近某一项
