### ISSUE TITLE
延时加载数据"循环"和"居中"不正常

### ISSUE THREAD

**Issue by JohnnyHooo** [12207480/TYCyclePagerView#7]
- (void)loadData {
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        NSMutableArray *datas = [NSMutableArray array];
        for (int i = 0; i < 5; ++i) {
            if (i == 0) {
                [datas addObject:[UIColor redColor]];
                continue;
            }
            [datas addObject:[UIColor colorWithRed:arc4random()%255/255.0 green:arc4random()%255/255.0 blue:arc4random()%255/255.0 alpha:arc4random()%255/255.0]];
        }
        _datas = [datas copy];
        //    _pageControl.numberOfPages = _datas.count;
        [_pagerView reloadData];
    });
   
}

- (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView {
    TYCyclePagerViewLayout *layout = [[TYCyclePagerViewLayout alloc]init];
    layout.layoutType = TYCyclePagerTransformLayoutLinear;
    layout.itemSpacing = 45;
    layout.minimumAlpha = 0.0;
    layout.itemHorizontalCenter = YES;
    layout.itemSize = CGSizeMake(200, CGRectGetHeight(pageView.frame));
    return layout;
}

这样设置会有BUG,

**Comment by JohnnyHooo** [comment]
minimumAlpha 属性好像没有生效

**Comment by 12207480** [comment]
已修复延时加载数据显示不对

**Comment by 12207480** [comment]
TYCyclePagerTransformLayoutNormal 对minimumAlpha 不起作用。
已修复其他layout type minimumAlpha 。
