### ISSUE TITLE
同一个页面两个 pageview时候，一个需要自动滚动，一个不需要，当前无法同时满足

### ISSUE THREAD

**Issue by 278956952** [12207480/TYCyclePagerView#71]

**Comment by 12207480** [comment]
可以吧

**Comment by 278956952** [comment]
嗯，我重新调整了，可以了 在2018年12月19日 17:14 ，yeBlueColor写道： 可以吧 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
