### ISSUE TITLE
pageView.curIndex 获取的不准确

### ISSUE THREAD

**Issue by iccpeng** [12207480/TYCyclePagerView#75]
快速滚动下  - (void)pagerViewDidEndDragging:(TYCyclePagerView *)pageView willDecelerate:(BOOL)decelerate 代理中获取的 pageView.curIndex 不准确

**Comment by 12207480** [comment]
pagerViewDidEndDecelerating
pagerViewDidEndScrollingAnimation
停下来在这里调用比较好
