### ISSUE TITLE
滚动crash

### ISSUE THREAD

**Issue by xiuqiao** [12207480/TYCyclePagerView#76]
当代理实现了scrollViewDidScroll 时校验代理实现的的方法为 
 _delegateFlags.pagerViewDidScroll = [delegate respondsToSelector:@selector(scrollViewDidScroll:)];  因此该标示为 YES 
调用时调用的是 pagerViewDidScroll: 不是校验的方法
  if (_delegateFlags.pagerViewDidScroll) {
        [_delegate pagerViewDidScroll:self];
    }

**Comment by 12207480** [comment]
是的 写错了

**Comment by 12207480** [comment]
最新版本已经改了的
