### ISSUE TITLE
layoutType 类型设置了没有效果

### ISSUE THREAD

**Issue by liyang521** [12207480/TYCyclePagerView#82]
我初始化的时候设置了layoutType = TYCyclePagerTransformLayoutLinear; 为什么没有效果呢 大神

**Comment by liuluchang** [comment]
遇到了同样的问题

**Comment by liyang521** [comment]
- (TYCyclePagerViewLayout *)layoutForPagerView:(TYCyclePagerView *)pageView {
}你在代理里设置就好了

**Comment by liuluchang** [comment]
我设置后出现了item大小计算不合适的问题，你有遇到吗
![1111](https://user-images.githubusercontent.com/8243170/58935295-afc53e80-879f-11e9-9b21-016559ddfba6.png)

**Comment by liyang521** [comment]
item 大小我是根据pageView宽高比例来的 然后设置itemSpacing

**Comment by liuluchang** [comment]
整合适了，看了下层级，由于我imageview大小使用自动布局导致约束不合适，但是控件的选项卡大小是合适的，重新改了下布局合适了！多谢！！！
