### ISSUE TITLE
一直都是从第四张图片开始

### ISSUE THREAD

**Issue by ZSMHup** [12207480/TYCyclePagerView#9]
只要图片大于四张，就会从第四张图片开始，不会从第一张开始

**Comment by 12207480** [comment]
是否下载的最新的版本？ 
这种情况这么复现的？

**Comment by ZSMHup** [comment]
解决了，当有导航栏的时候就会有这种情况，pagerView的frame在初始化的时候设置，不要在viewWillLayoutSubviews里设置

**Comment by 12207480** [comment]
恩  将会解决这个问题

**Comment by ZSMHup** [comment]
能加个qq吗？403549384
