### ISSUE TITLE
minimumScale 不起作用

### ISSUE THREAD

**Issue by CoderPby** [12207480/TYCyclePagerView#91]
layoutType 为 TYCyclePagerTransformLayoutLinear，虽然设置了 minimumScale，但是缩放不会达到这个比例（size 都偏大）。请问有办法控制可以达到这个比例，或者是直接设置未选中 cell 的大小吗？比如 itemSize 为（100，100），选中的 cell 的 size 也是（100，100），其他未选中的 cell 的 size 能否直接设置为（50，50）？

**Comment by 12207480** [comment]
还不行
