### ISSUE TITLE
只有一个item 时，还在循环滚动

### ISSUE THREAD

**Issue by Suzhibin** [12207480/TYCyclePagerView#92]
只有一个item 时，还在循环滚动，感觉很怪异，如果只有一个item 时，能设置成不滚动吗

**Comment by Suzhibin** [comment]
找到解决办法了 我在请求完数据时。设置了一下
if (self.datas.count==1) {
        _pagerView.isInfiniteLoop = NO;
    }else{
        _pagerView.isInfiniteLoop = YES;
    }
  [_pagerView reloadData];

**Comment by 12207480** [comment]
是的
